# Generated by Django 5.2.7 on 2025-10-23 08:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import helper_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtesyLink',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(default=helper_functions.generate_courtesy_code, max_length=100, unique=True)),
                ('ticket_count', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'courtesy_links',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('courtesy', 'Courtesy')], default='pending', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courtesy_link_id', models.ForeignKey(blank=True, db_column='courtesy_link_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.courtesylink')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
