# Generated by Django 5.2.7 on 2025-10-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('to', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('text', models.TextField()),
                ('attachments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_queue',
            },
        ),
        migrations.AddField(
            model_name='courtesylink',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
