# Generated by Django 5.2.7 on 2025-10-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField()),
                ('qr_code_s3_url', models.CharField(blank=True, max_length=500)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
