# Generated by Django 5.2.7 on 2025-10-22 20:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        ('orders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtesyAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('partner_company', models.CharField(blank=True, max_length=255, null=True)),
                ('event_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Courtesy Attendee',
                'verbose_name_plural': 'Courtesy Attendees',
                'db_table': 'courtesy_attendees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('first batch', 'First Batch'), ('second batch', 'Second Batch'), ('third batch', 'Third Batch'), ('coupon', 'Coupon'), ('courtesy', 'Courtesy')], max_length=20)),
                ('qr_code_data', models.TextField()),
                ('qr_code_s3_url', models.CharField(blank=True, max_length=500)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
