# Generated by Django 5.2.7 on 2025-10-20 06:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtesyAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('partner_company', models.CharField(blank=True, max_length=255, null=True)),
                ('event_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Courtesy Attendee',
                'verbose_name_plural': 'Courtesy Attendees',
                'db_table': 'courtesy_attendees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
